routes.py
import uuid
from flask import (
    Blueprint, render_template, session, redirect, 
    request, current_app, url_for, flash
)
from dataclasses import asdict
from forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from models import Movie, User
import datetime
import functools
from passlib.hash import pbkdf2_sha256


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route("/")
@login_required
def index():
    user_data = current_app.db.users.find_one({"email": session["email"]})
    user = User(**user_data)

    movie_data = current_app.db.movies.find({"_id": {"$in": user.movies}})
    movies = [Movie(**movie) for movie in movie_data]

    return render_template(
        "index.html",
        title="Movies Watchlist",
        movies_data=movies
    )

@pages.route("/register", methods=["POST", "GET"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.users.insert_one(asdict(user))

        flash("User registered successfully", "success")

        #change to index after
        return redirect(url_for(".login"))

    return render_template("register.html", title="Movies Watchlist - Register", form=form)

@pages.route("/login", methods=["GET", "POST"]) 
def login():
    if session.get("email"):
        return redirect(url_for(".index"))
    
    form = LoginForm()
    if form.validate_on_submit():
        user_data = current_app.db.users.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials are not correct", category="danger")
            return redirect(url_for(".login"))
        
        user = User(**user_data)
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))
        
        flash("Login credentials are not correct", category="danger")

    return render_template("login.html", title="Movies Watchlist - Login", form=form)

@pages.route("/logout")
def logout():
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme

    return redirect(url_for(".login"))

@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data
        )

        current_app.db.movies.insert_one(asdict(movie))
        current_app.db.users.update_one(
            {"_id": session["user_id"]}, 
            {"$push": {"movies": movie._id}}
        )

        return redirect(url_for(".index"))

    return render_template(
        "new_movie.html", 
        title="Movies Watchlist - Add Movie", 
        form=form
    )

@pages.get("/browse")
def browse_movies():
    movie_data = current_app.db.movies.find()
    movies = [Movie(**movie) for movie in movie_data]

    return render_template(
        "browse.html",
        title="Browse Movies",
        movies=movies
    )

@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)
    form = ExtendedMovieForm(obj=movie)

    if form.validate_on_submit():
        movie.title = form.title.data
        movie.description = form.description.data
        movie.year = form.year.data
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data

        current_app.db.movies.update_one(
            {"_id": movie._id}, 
            {"$set": asdict(movie)}
            )
        return redirect(url_for(".movie", _id=movie._id))
    
    return render_template("movieForm.html", movie=movie, form=form)


@pages.get("/movie/<string:_id>")
def movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)
    return render_template("movieDetails.html", movie=movie)

@pages.get("/movie/<string:_id>/rate")
def rate_movie(_id: str):
    if not session.get("email"):
        return redirect(url_for('pages.login'))

    rating = int(request.args.get("rating"))
    current_app.db.movies.update_one({"_id": _id}, {"$set": {"rating": rating}})

    return redirect(url_for("pages.movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
def watch_today(_id: str):
    if not session.get("email"):
        return redirect(url_for('pages.login'))

    current_app.db.movies.update_one({"_id": _id}, {"$set": {"last_watched": datetime.datetime.today()}})

    return redirect(url_for("pages.movie", _id=_id))
 


@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

templates/browse.html
{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/browse.css') }}">
{% endblock %}

{% block main_content %}
<h1>{{ title }}</h1>

    {% if movies %}
        <ul class="movie-list">
            {% for movie in movies %}
            <li class="movie-item">
                <a class="movie-link" href="{{ url_for('pages.movie', _id=movie._id) }}">
                    <div class="movie-info">
                        <h2 class="movie-title">{{ movie.title }}</h2>
                        <p class="movie-details">Directed by {{ movie.director }} ({{ movie.year }})</p>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No movies available.</p>
    {% endif %}

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movies.css') }}" />
{% endblock %}

{% block main_content %}
    {% if movies_data %}
        <table class="table">
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            
            <thead>
                <th class="table-cell table-cell-header">Title</th>
                <th class="table-cell table-cell-header">Release Date</th>
                <th class="table-cell table-cell-header"></th>
            </thead>

            <tbody>
                {% for movie in movies_data %}
                    <tr>
                        <td class="table-cell">
                            <p class="table-movieTitle">{{ movie.title }}</p>
                            <p class="table-movieDirector">{{ movie.director }}</p>
                        </td>
                        <td class="table-cell table-movieYear">{{ movie.year}}</td>
                        <td class="table-cell">
                            <a href="{{ url_for('pages.movie', _id=movie._id) }}" class="table-link">View</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="table-empty">You haven't added any movies yet. <a href="{{ url_for('pages.add_movie')}}" class="link">Add one!</a></p>
    {% endif %}

    <a href="{{ url_for('pages.add_movie') }}" class="button button-add">
        <span>+</span>
    </a>
{% endblock %}

templates/layout.html
{% from 'macros/nav.html' import header %}
{% from 'macros/footer.html' import footer %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark'}}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        {{ header(session.get("email"), session.get("theme")) }}
        <main class="main">
            {% block main_content %} {% endblock %}
        </main>
        {{ footer() }}
    </body>
</html>

templates/login.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form-flash form-flash-{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        
        <div class="form-container">
            {{ form.hidden_tag() }}

            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form-small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form-link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button-form") }}
            </div>
        </div>
    </form>

{% endblock %}

templates/movieDetails.html
{% from 'macros/svgs.html' import star, pencil %}

{% extends 'layout.html' %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movieDetails.css') }}">
{% endblock %}

{% block main_content %}
    <div class="container">
        <header class="movie-header">
            <div class="header-row">
                <div class="movie-name">
                    <h1>{{ movie.title }}</h1>
                    <div class="movie-rating">
                        {% for i in range(5) %}
                            {% if session.email %}
                                <a class="rating-link" href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}">
                                    {{ star("star " + ("star-filled" if movie.rating > i else "")) }}
                                </a>
                            {% else %}
                                <a class="rating-link" href="{{ url_for('pages.login') }}">
                                    {{ star("star " + ("star-filled" if 0 > i else "")) }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="movie-watched">
                    {% if session.email %}
                        {% if movie.last_watched %}
                            <p>
                                Last watched: <a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched-link">                                
                                    <time datetime="{{ movie.last_watched }}">{{ movie.last_watched.strftime("%d %b %Y") }}</time>
                                </a>
                            </p>
                        {% else %}
                            <p><a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched-link">Not watched yet</a></p>
                        {% endif %}
                    {% else %}
                        <p>Last watched: <a href="{{ url_for('pages.login') }}" class="watched-link">Log in to track</a></p>
                    {% endif %}
                    <a class="movie-edit" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Edit {{ pencil("pencil") }}</a>
                </div>
            </div>
            <div class="header-row">
                <ul class="movie-tags">
                {% for tag in movie.tags %}
                    <li class="movie-tag">{{ tag }}</li>
                {% endfor %}
                </ul>
            </div>
        </header>

        {% if movie.video_link %}
            <iframe
                class="movie-video"
                src="{{ movie.video_link }}"
                title="YouTube video player"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
            </iframe>
        {% endif %}

        {% if movie.description %}
            <p class="movie-description">{{ movie.description }}</p>
        {% else %}
            <p class="movie-description">No description yet. <a class="link" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Add one?</a></p>
        {% endif %}

        <div class="movie-meta">
            {% if movie.cast %}
                <div class="movie-casting">
                    <h2>Casting</h2>
                    <ul class="list">
                    {% for actor in movie.cast %}
                        <li class="list-item">{{ actor }}</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if movie.series | length %}
                <div class="movie-series">
                    <h2>Series</h2>
                    <ul class="list">
                    {% for movie_in_series in movie.series %}
                        <li class="list-item">{{ movie_in_series }}</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/movieForm.html
{% from "macros/fields.html" import render_text_field, render_area_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="add_movie" method="post" novalidate class="form">
        <div class="form-container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            {{ render_area_field(form.cast) }}
            {{ render_area_field(form.series) }}
            {{ render_area_field(form.tags) }}

            {{ render_area_field(form.description) }}
            {{ render_text_field(form.video_link) }}
    
            <div>
                {{ form.submit(class_="button button-form") }}
            </div>
        </div>
    </form>

{% endblock %}

templates/new_movie.html
{% from 'macros/fields.html' import render_text_field %}

{% extends 'layout.html' %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}"
{% endblock %}

{% block main_content %}
    <form name="add-movie" method="post" novalidate class="form">
        <div class="form-container">
            <!-- protect form from an attacker -->
            {{ form.hidden_tag() }}

            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            <div>
                {{ form.submit(class_="button button-form") }}
            </div>
        </div>
    </form>
{% endblock %}

templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form-flash form-flash-{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        
        <div class="form-container">
            {{ form.hidden_tag() }}

            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}
    
            <span class="form-small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form-link">Log in here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button-form") }}
            </div>
        </div>
    </form>

{% endblock %}